# Generated by Django 6.0.4 on 2026-04-26 03:30

import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('pan', 'PAN Card'), ('aadhaar', 'Aadhaar Card'), ('bank_statement', 'Bank Statement'), ('business_proof', 'Business Proof')], max_length=30)),
                ('file', models.FileField(upload_to=kyc.models.document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('business_address', models.TextField(blank=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_info_requested', 'More Info Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('more_info_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
