# Generated by Django 6.0.4 on 2026-04-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Submission Created'), ('submitted', 'Submitted for Review'), ('picked_up', 'Picked Up for Review'), ('approve', 'Approved'), ('reject', 'Rejected'), ('request_info', 'More Info Requested'), ('document_uploaded', 'Document Uploaded'), ('comment', 'Comment Added')], max_length=30)),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
